//
// Created by 11896 on 15/11/2024.
//

#ifndef BLOCKYENGINE_ELLIPSERENDERABLE_HPP
#define BLOCKYENGINE_ELLIPSERENDERABLE_HPP


class EllipseRenderable {
    
};


#endif //BLOCKYENGINE_ELLIPSERENDERABLE_HPP
