//
// Created by 11896 on 15/11/2024.
//

#ifndef BLOCKYENGINE_RENDERABLETYPE_HPP
#define BLOCKYENGINE_RENDERABLETYPE_HPP

enum RenderableType{
    RECTANGLE,
    ELLIPSE,
    SPRITE
};

#endif //BLOCKYENGINE_RENDERABLETYPE_HPP
