//
// Created by 11896 on 27/11/2024.
//

#ifndef BLOCKYENGINE_ENGINE_MODULEMANAGER_MODULES_INPUT_MOUSEINPUT_HPP_
#define BLOCKYENGINE_ENGINE_MODULEMANAGER_MODULES_INPUT_MOUSEINPUT_HPP_

#include "SDL_mouse.h"

enum class MouseInput {
	BUTTON_LEFT,
	BUTTON_RIGHT,
	BUTTON_MIDDLE
};

MouseInput SDLMouseButtonToCustomMouseButton(Uint8 sdlButton);


#endif //BLOCKYENGINE_ENGINE_MODULEMANAGER_MODULES_INPUT_MOUSEINPUT_HPP_
