//
// Created by 11896 on 05/12/2024.
//

#ifndef BLOCKYENGINE_ENGINE_COMPONENTS_GUI_UICOMPONENT_HPP_
#define BLOCKYENGINE_ENGINE_COMPONENTS_GUI_UICOMPONENT_HPP_

#include <imgui/imgui.h>

class UIComponent {

};



#endif //BLOCKYENGINE_ENGINE_COMPONENTS_GUI_UICOMPONENT_HPP_
