//
// Created by 11896 on 19/11/2024.
//

#ifndef BLOCKYENGINE_ENGINE_COMPONENTS_ANIMATION_ANIMATOR_HPP_
#define BLOCKYENGINE_ENGINE_COMPONENTS_ANIMATION_ANIMATOR_HPP_

class Animator {

};

#endif //BLOCKYENGINE_ENGINE_COMPONENTS_ANIMATION_ANIMATOR_HPP_
