//
// Created by 11896 on 19/11/2024.
//

#ifndef BLOCKYENGINE_ENGINE_COMPONENTS_ANIMATION_ANIMATION_HPP_
#define BLOCKYENGINE_ENGINE_COMPONENTS_ANIMATION_ANIMATION_HPP_

class Animation {

};

#endif //BLOCKYENGINE_ENGINE_COMPONENTS_ANIMATION_ANIMATION_HPP_
